images:
  mep:
    repository: edgegallery/mep
    tag: latest
    pullPolicy: Always
  kong:
    repository: kong
    tag: 1.5.1-alpine
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: 12.2
    pullPolicy: IfNotPresent
persistence:
  enabled: false
  storageClassName: nfs-client
postgres:
  username: kong
  password: te9Fmv%qaq
  dbname: kongdb
ssl:
  enabled: false
  secretName: