
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-plugin
  namespace: default
  labels:
    app: helm-plugin
spec:
  selector:
    matchLabels:
      app: helm-plugin
  replicas: 1
  template:
    metadata:
      labels:
        app: helm-plugin
    spec:
      containers:
        - name: mecm-helm-plugin
          image: {{ .Values.images.helmplugin.repository }}:{{ .Values.images.helmplugin.tag }}
          imagePullPolicy: {{ .Values.images.helmplugin.pullPolicy }}
          env:
            - name: LOGFILE_PATH
              value: /usr/helmplugin/logfile
            - name: LOGGER_LEVEL
              value: info
            - name: ADDRESS
              value: 0.0.0.0:8081
            - name: SSL_ENABLED
              value: {{ quote .Values.ssl.enabled }}
            {{- if .Values.ssl.enabled }}
            - name: CERTIFICATE_PATH
              value: /usr/helmplugin/ca-certificates/server.cer
            - name: KEY_PATH
              value: /usr/helmplugin/ca-certificates/server_key.pem
            {{- end }}
            - name: PACKAGE_PATH
              value: /usr/helmplugin/packages/
            - name: PACKAGE_ARTIFACT_PATH
              value: /Artifacts/Deployment/
            - name: CHART_PATH
              value: /usr/helmplugin/charts/
            - name: KUBECONFIG_DIR_PATH
              value: /usr/helmplugin/kubeconfig/
            - name: RELEASE_NAMESPACE
              value: default
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.publicKeySecretName }}
                  key: publicKey
          ports:
          - containerPort: 8081
          volumeMounts:
            {{- if .Values.ssl.enabled }}
            - mountPath: /usr/helmplugin/ca-certificates
              name: helm-plugin-server-cert
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: helm-plugin-log
              mountPath: /var/log/helm-plugin
            {{- end }}


      volumes:
        {{- if .Values.ssl.enabled }}
        - name: helm-plugin-server-cert
          secret:
            secretName: {{ .Values.ssl.secretName }}
            items:
              - key: server.cer
                path: server.cer
              - key: server_key.pem
                path: server_key.pem
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: helm-plugin-log
          hostPath:
            path: /var/log/edgegallery/helmplugin
        {{- end }}


