images:
  applcm:
    repository: edgegallery/mecm-applcm
    tag: latest
    pullPolicy: Always
  helmplugin:
    repository: edgegallery/mecm-helm-plugin
    tag: latest
    pullPolicy: Always
persistence:
  enabled: true
expose:
  applcm:
    port: 8282
    nodePort: 30101
  helmplugin:
    port: 8081
    nodePort: 30201
jwt:
  publicKeySecretName:
ssl:
  enabled: false
  secretName: